services:
  postgres:
    image: postgres:15
    container_name: whaticket_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"

  redis:
    image: redis:7
    container_name: whaticket_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASS}
    volumes:
      - redisdata:/data

  whaticket_backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
      - redis
    environment:
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - TZ=${TZ}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - PORT=${BACK_PORT}
      - PROXY_PORT=${PROXY_PORT}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - CHROME_ARGS=${CHROME_ARGS}
      - REDIS_URI=${REDIS_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_OPT_LIMITER_MAX=${REDIS_OPT_LIMITER_MAX}
      - REDIS_OPT_LIMITER_DURATION=${REDIS_OPT_LIMITER_DURATION}
      - GERENCIANET_SANDBOX=${GERENCIANET_SANDBOX}
      - GERENCIANET_CLIENT_ID=${GERENCIANET_CLIENT_ID}
      - GERENCIANET_CLIENT_SECRET=${GERENCIANET_CLIENT_SECRET}
      - GERENCIANET_PIX_CERT=${GERENCIANET_PIX_CERT}
      - GERENCIANET_PIX_KEY=${GERENCIANET_PIX_KEY}
      - USER_LIMIT=${USER_LIMIT}
      - CONNECTIONS_LIMIT=${CONNECTIONS_LIMIT}
      - CLOSED_SEND_BY_ME=${CLOSED_SEND_BY_ME}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_PORT=${MAIL_PORT}
    ports:
      - "${BACK_PORT}:${BACK_PORT}"

  whaticket_frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      args:
        BACKEND_URL: ${BACKEND_URL}
        REACT_APP_HOURS_CLOSE_TICKETS_AUTO: ${REACT_APP_HOURS_CLOSE_TICKETS_AUTO}
    environment:
      - FROT_PORT=${FROT_PORT}
      - BACKEND_URL=${BACKEND_URL}
      - REACT_APP_HOURS_CLOSE_TICKETS_AUTO=${REACT_APP_HOURS_CLOSE_TICKETS_AUTO}
    ports:
      - "${FROT_PORT}:${FROT_PORT}"

volumes:
  pgdata:
  redisdata:
